name Create backup archive

on
  push
    branches
      - main

jobs
  backup
    runs-on ubuntu-latest

    steps
      - name Получение кода
        uses actionscheckout@v4

      - name Создание архива
        run zip -r backup.zip .

      - name Сохранение архива в облаке GitHub
        uses actionsupload-artifact@v4
        with
          name site-backup
          path backup.zip
